# Generated by Django 6.0.1 on 2026-02-05 22:54
# Modified to only create LLMModel - geographic models moved to audiences app

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Only create LLMModel - Language and other geographic models
        # are now in the audiences app
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="HuggingFace model ID (e.g., 'Qwen/Qwen2.5-7B-Instruct').", max_length=200, unique=True)),
                ('name', models.CharField(help_text="Friendly display name (e.g., 'Qwen 2.5 7B').", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes about model capabilities, strengths, or limitations.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'db_table': 'core_llmmodel',
                'ordering': ['name'],
            },
        ),
    ]
