# Generated by Django 6.0.1 on 2026-02-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="HuggingFace model ID (e.g., 'Qwen/Qwen2.5-7B-Instruct').", max_length=200, unique=True)),
                ('name', models.CharField(help_text="Friendly display name (e.g., 'Qwen 2.5 7B').", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes about model capabilities, strengths, or limitations.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'db_table': 'core_llmmodel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="ISO 639-1 language code (e.g., 'ja', 'de', 'es-MX').", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Language name (e.g., 'Japanese', 'German').", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Notes about language-specific considerations.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is available for adaptations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_models', models.ManyToManyField(blank=True, help_text='Alternative models that can also handle this language.', related_name='alternative_for_languages', to='core.llmmodel')),
                ('primary_model', models.ForeignKey(help_text='Recommended model for this language.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_languages', to='core.llmmodel')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'core_language',
                'ordering': ['name'],
            },
        ),
    ]
