# Generated by Django 6.0.1 on 2026-02-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='load_in_4bit',
            field=models.BooleanField(default=False, help_text='Load model with 4-bit quantization (requires bitsandbytes).'),
        ),
    ]
