# Generated by Django 6.0.1 on 2026-02-09 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_llmmodel_load_in_4bit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Template identifier (e.g., 'adaptation', 'concept-extraction')",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Cultural Adaptation')",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("enhancement", "Prompt Enhancement"),
                            ("adaptation", "Cultural Adaptation"),
                            ("evaluation", "Quality Evaluation"),
                            ("concept", "Concept Analysis"),
                        ],
                        help_text="Template category",
                        max_length=50,
                    ),
                ),
                ("template", models.TextField(help_text="Jinja2 template content")),
                (
                    "expected_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Expected template variables: {name: {type, required, description}}",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Template version number (auto-incremented on save)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this version is the active version",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Purpose and usage notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this template has been rendered",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this template was rendered",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this template version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_prompt_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "db_table": "core_prompttemplate",
                "ordering": ["-version", "slug"],
                "indexes": [
                    models.Index(
                        fields=["slug", "is_active"], name="core_prompt_slug_49ce9c_idx"
                    ),
                    models.Index(
                        fields=["category"], name="core_prompt_categor_929578_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "version"), name="unique_slug_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("slug",),
                        name="unique_active_slug",
                    ),
                ],
            },
        ),
    ]
