# Generated by Django 6.0.1 on 2026-02-07 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_llmmodel_load_in_4bit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Slug identifier (e.g., 'nordic-minimalism')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Nordic Minimalism')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of cultural characteristics"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "db_table": "core_culture",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., 'NA', 'NORDICS', 'DACH')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'North America')", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Region description and scope"
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=list,
                        help_text="Regional cultural patterns: [{heading, points[]}]",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "core_region",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegionCulture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region-Culture Mapping",
                "verbose_name_plural": "Region-Culture Mappings",
                "db_table": "core_region_culture",
            },
        ),
        migrations.AddField(
            model_name="language",
            name="base_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 639-1 base language code (e.g., 'en', 'fr', 'de')",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="insights",
            field=models.JSONField(
                default=list,
                help_text="Language-specific localization guidance: [{heading, points[]}]",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                help_text="ISO 639 + country locale (e.g., 'en-US', 'fr-CA')",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(
                help_text="Display name (e.g., 'English (United States)')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="primary_model",
            field=models.ForeignKey(
                help_text="Recommended LLM model for this language",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_for_languages",
                to="core.llmmodel",
            ),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code (e.g., 'US', 'CA', 'SE')",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Official country name", max_length=100),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=list,
                        help_text="Country-specific regulatory and cultural rules: [{heading, points[]}]",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary/default language for this country",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_countries",
                        to="core.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "core_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CountryLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary/official language for this country",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.language"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country-Language Mapping",
                "verbose_name_plural": "Country-Language Mappings",
                "db_table": "core_country_language",
            },
        ),
        migrations.AddField(
            model_name="country",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="All languages spoken in this country",
                related_name="countries",
                through="core.CountryLanguage",
                to="core.language",
            ),
        ),
        migrations.CreateModel(
            name="CountryRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country-Region Mapping",
                "verbose_name_plural": "Country-Region Mappings",
                "db_table": "core_country_region",
            },
        ),
        migrations.CreateModel(
            name="LanguageAlternativeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.language"
                    ),
                ),
                (
                    "llmmodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.llmmodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Alternative Model",
                "verbose_name_plural": "Language Alternative Models",
                "db_table": "core_language_alternative_model",
            },
        ),
        # Remove old alternative_models M2M field (cannot alter to add through)
        migrations.RemoveField(
            model_name="language",
            name="alternative_models",
        ),
        # Add new alternative_models M2M field with through table
        migrations.AddField(
            model_name="language",
            name="alternative_models",
            field=models.ManyToManyField(
                blank=True,
                help_text="Alternative LLM models that can handle this language",
                related_name="alternative_for_languages",
                through="core.LanguageAlternativeModel",
                to="core.llmmodel",
            ),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(
                fields=["base_language", "is_active"], name="lang_base_active_idx"
            ),
        ),
        migrations.AddField(
            model_name="countryregion",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.region"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regions this country belongs to",
                related_name="countries",
                through="core.CountryRegion",
                to="core.region",
            ),
        ),
        migrations.AddField(
            model_name="regionculture",
            name="culture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.culture"
            ),
        ),
        migrations.AddField(
            model_name="regionculture",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.region"
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regions associated with this culture",
                related_name="cultures",
                through="core.RegionCulture",
                to="core.region",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="countrylanguage",
            unique_together={("country", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="languagealternativemodel",
            unique_together={("language", "llmmodel")},
        ),
        migrations.AlterUniqueTogether(
            name="countryregion",
            unique_together={("country", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="regionculture",
            unique_together={("region", "culture")},
        ),
    ]
