# Generated by Django 6.0.1 on 2026-02-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_old_alternative_models"),
    ]

    operations = [
        # Remove unique_together constraint first (while fields still exist)
        migrations.AlterUniqueTogether(
            name="regionculture",
            unique_together=set(),
        ),
        # Now remove the fields
        migrations.RemoveField(
            model_name="regionculture",
            name="culture",
        ),
        migrations.RemoveField(
            model_name="regionculture",
            name="region",
        ),
        # Finally delete the models
        migrations.DeleteModel(
            name="Culture",
        ),
        migrations.DeleteModel(
            name="RegionCulture",
        ),
    ]
