# Generated by Django 6.0.1 on 2026-02-09 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prompttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_gate_default_model', models.ForeignKey(blank=True, help_text='Default model for Brand Gate node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
                ('concept_default_model', models.ForeignKey(blank=True, help_text='Default model for Concept Analyst node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
                ('concept_gate_default_model', models.ForeignKey(blank=True, help_text='Default model for Concept Gate node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
                ('culture_default_model', models.ForeignKey(blank=True, help_text='Default model for Cultural Researcher node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
                ('culture_gate_default_model', models.ForeignKey(blank=True, help_text='Default model for Culture Gate node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
                ('format_gate_default_model', models.ForeignKey(blank=True, help_text='Default model for Format Gate node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
                ('global_default_model', models.ForeignKey(blank=True, help_text='Fallback model when no node-specific default is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.llmmodel')),
            ],
            options={
                'verbose_name': 'Pipeline Settings',
                'verbose_name_plural': 'Pipeline Settings',
                'db_table': 'core_pipelinesettings',
            },
        ),
    ]
