# Generated by Django 6.0.1 on 2026-02-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_drop_culture_model"),
        ("tvspots", "0003_alter_adunit_country_alter_adunit_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="default_language",
        ),
        migrations.RemoveField(
            model_name="country",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="country",
            name="regions",
        ),
        migrations.RemoveField(
            model_name="countryregion",
            name="country",
        ),
        migrations.RemoveField(
            model_name="countrylanguage",
            name="country",
        ),
        migrations.AlterUniqueTogether(
            name="countrylanguage",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="countrylanguage",
            name="language",
        ),
        migrations.AlterUniqueTogether(
            name="countryregion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="countryregion",
            name="region",
        ),
        migrations.RemoveIndex(
            model_name="language",
            name="lang_base_active_idx",
        ),
        migrations.RemoveField(
            model_name="languagealternativemodel",
            name="language",
        ),
        migrations.AlterUniqueTogether(
            name="languagealternativemodel",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="languagealternativemodel",
            name="llmmodel",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="CountryLanguage",
        ),
        migrations.DeleteModel(
            name="CountryRegion",
        ),
        migrations.DeleteModel(
            name="Region",
        ),
        migrations.RemoveField(
            model_name="language",
            name="alternative_models",
        ),
        migrations.RemoveField(
            model_name="language",
            name="primary_model",
        ),
        migrations.DeleteModel(
            name="LanguageAlternativeModel",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
