# Generated by Django 6.0.1 on 2026-02-05 20:28

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiffusionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name for the model', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier', max_length=100, unique=True)),
                ('base_architecture', models.CharField(choices=[('sdxl', 'SDXL'), ('sd15', 'SD 1.5'), ('flux1', 'Flux.1'), ('qwen', 'Qwen'), ('zimage', 'Z-Image (Lumina/S3-DiT)')], default='sdxl', help_text='Base model architecture (determines LoRA compatibility)', max_length=20)),
                ('path', models.CharField(help_text="HuggingFace model ID (e.g., 'Qwen/Qwen-Image-2512') or local path", max_length=500)),
                ('pipeline', models.CharField(help_text="Pipeline class name (e.g., 'ZImagePipeline', 'FluxPipeline')", max_length=100)),
                ('steps', models.IntegerField(default=28, help_text='Default number of inference steps', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('guidance_scale', models.FloatField(default=3.5, help_text='Default guidance scale (CFG)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('default_width', models.IntegerField(default=1024, help_text='Default image width in pixels', validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('default_height', models.IntegerField(default=1024, help_text='Default image height in pixels', validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('max_pixels', models.IntegerField(default=1048576, help_text='Maximum total pixels (width * height)')),
                ('scheduler', models.CharField(blank=True, choices=[('', '— Use pipeline default —'), ('EulerDiscreteScheduler', 'Euler'), ('EulerAncestralDiscreteScheduler', 'Euler Ancestral'), ('DPMSolverMultistepScheduler', 'DPM++ 2M'), ('DPMSolverSinglestepScheduler', 'DPM++ SDE'), ('KDPM2DiscreteScheduler', 'DPM2'), ('KDPM2AncestralDiscreteScheduler', 'DPM2 Ancestral'), ('FlowMatchEulerDiscreteScheduler', 'Flow Match Euler'), ('DDIMScheduler', 'DDIM'), ('DDPMScheduler', 'DDPM'), ('PNDMScheduler', 'PNDM'), ('HeunDiscreteScheduler', 'Heun'), ('LMSDiscreteScheduler', 'LMS'), ('UniPCMultistepScheduler', 'UniPC'), ('LCMScheduler', 'LCM')], default='', help_text='Default scheduler for this model', max_length=100)),
                ('dtype', models.CharField(choices=[('bfloat16', 'BFloat16'), ('float16', 'Float16'), ('float32', 'Float32'), ('float8_e4m3fn', 'Float8 (E4M3)')], default='bfloat16', help_text='Data type for model weights', max_length=50)),
                ('supports_negative_prompt', models.BooleanField(default=False, help_text='Whether this model supports negative prompts')),
                ('force_default_guidance', models.BooleanField(default=False, help_text="Force model's default guidance_scale (Turbo models). Prevents LoRA/job overrides.")),
                ('max_sequence_length', models.IntegerField(blank=True, help_text='Maximum sequence length for text encoder', null=True)),
                ('token_window', models.IntegerField(blank=True, help_text='Maximum tokens for prompt input (e.g. 77 for CLIP, 512 for T5)', null=True)),
                ('vram_usage', models.IntegerField(blank=True, help_text='Minimum VRAM required in MB (e.g. 8192 for 8GB)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diffusion Model',
                'verbose_name_plural': 'Diffusion Models',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='LoraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name for the LoRA', max_length=255)),
                ('path', models.CharField(blank=True, help_text='Path to LoRA file (relative to base_model_path or HF model ID). Optional if AIR is provided.', max_length=500)),
                ('air', models.CharField(blank=True, help_text='AIR (AI Resource) URN identifier', max_length=500)),
                ('base_architecture', models.CharField(choices=[('sdxl', 'SDXL'), ('sd15', 'SD 1.5'), ('flux1', 'Flux.1'), ('qwen', 'Qwen'), ('zimage', 'Z-Image (Lumina/S3-DiT)')], default='sdxl', help_text='Base model architecture this LoRA is trained for', max_length=20)),
                ('prompt_suffix', models.TextField(blank=True, help_text='Trigger words and style description to append to prompts')),
                ('negative_prompt_suffix', models.TextField(blank=True, help_text='Terms to append to negative prompts (only applied when model supports negative prompts)')),
                ('default_strength', models.FloatField(default=0.8, help_text='Default LoRA strength/weight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('guidance_scale', models.FloatField(blank=True, help_text='Override guidance scale (CFG) when using this LoRA. Leave blank to use model/job default.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('clip_skip', models.IntegerField(blank=True, help_text='Number of CLIP layers to skip (1-12). Leave blank to use model default. Commonly 1 or 2 for anime/artistic styles.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this LoRA (usage tips, characteristics, etc.)')),
                ('theme', models.CharField(blank=True, help_text="Theme or category for filtering (e.g., 'anime', 'photorealistic', 'fantasy')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this LoRA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LoRA Model',
                'verbose_name_plural': 'LoRA Models',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_prompt', models.TextField(help_text='Original user-provided prompt')),
                ('enhanced_prompt', models.TextField(blank=True, help_text='AI-enhanced version of the prompt')),
                ('negative_prompt', models.TextField(blank=True, help_text='Negative prompt (things to avoid)')),
                ('enhancement_style', models.CharField(choices=[('auto', 'Auto-detect'), ('photography', 'Photography'), ('artistic', 'Artistic'), ('realistic', 'Realistic'), ('cinematic', 'Cinematic'), ('coloring-book', 'Coloring Book')], default='auto', help_text='Style used for enhancement', max_length=50)),
                ('enhancement_method', models.CharField(choices=[('none', 'No Enhancement'), ('rule-based', 'Rule-based'), ('huggingface', 'HuggingFace Local Model'), ('llm', 'LLM API')], default='none', help_text='Method used to enhance the prompt', max_length=50)),
                ('creativity', models.FloatField(default=0.7, help_text='Creativity level for enhancement (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiffusionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, help_text="Optional identifier for file naming (e.g., 'hero-shot', 'product-v2')", max_length=100)),
                ('width', models.IntegerField(blank=True, help_text='Image width (uses model default if not set)', null=True, validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('height', models.IntegerField(blank=True, help_text='Image height (uses model default if not set)', null=True, validators=[django.core.validators.MinValueValidator(256), django.core.validators.MaxValueValidator(4096)])),
                ('steps', models.IntegerField(blank=True, help_text='Number of steps (uses model default if not set)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('guidance_scale', models.FloatField(blank=True, help_text='Guidance scale (uses model default if not set)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('lora_strength', models.FloatField(blank=True, help_text='LoRA strength (uses LoRA default if not set)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('seed', models.BigIntegerField(blank=True, help_text='Random seed for reproducibility (random if not set)', null=True)),
                ('scheduler', models.CharField(blank=True, choices=[('', '— Use pipeline default —'), ('EulerDiscreteScheduler', 'Euler'), ('EulerAncestralDiscreteScheduler', 'Euler Ancestral'), ('DPMSolverMultistepScheduler', 'DPM++ 2M'), ('DPMSolverSinglestepScheduler', 'DPM++ SDE'), ('KDPM2DiscreteScheduler', 'DPM2'), ('KDPM2AncestralDiscreteScheduler', 'DPM2 Ancestral'), ('FlowMatchEulerDiscreteScheduler', 'Flow Match Euler'), ('DDIMScheduler', 'DDIM'), ('DDPMScheduler', 'DDPM'), ('PNDMScheduler', 'PNDM'), ('HeunDiscreteScheduler', 'Heun'), ('LMSDiscreteScheduler', 'LMS'), ('UniPCMultistepScheduler', 'UniPC'), ('LCMScheduler', 'LCM')], default='', help_text='Override scheduler. Leave blank to use model default.', max_length=100)),
                ('num_images', models.IntegerField(default=1, help_text='Number of images to generate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current job status', max_length=20)),
                ('rq_job_id', models.CharField(blank=True, help_text='Celery task ID for tracking (field name retained for compatibility)', max_length=255)),
                ('result_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, help_text='List of generated image paths')),
                ('generation_metadata', models.JSONField(blank=True, help_text='Complete generation settings used (prompt, seed, parameters, etc.)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if job failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diffusion_model', models.ForeignKey(help_text='Model to use for generation', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='diffusion.diffusionmodel')),
                ('lora_model', models.ForeignKey(blank=True, help_text='Optional LoRA to apply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='diffusion.loramodel')),
                ('prompt', models.ForeignKey(help_text='Prompt to use for generation', on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='diffusion.prompt')),
            ],
            options={
                'verbose_name': 'Diffusion Job',
                'verbose_name_plural': 'Diffusion Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
