# Generated by Django 6.0.1 on 2026-02-13 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name for the ControlNet', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier', max_length=100, unique=True)),
                ('path', models.CharField(help_text="HuggingFace model ID (e.g., 'diffusers/controlnet-canny-sdxl-1.0')", max_length=500)),
                ('control_type', models.CharField(choices=[('canny', 'Canny Edge'), ('lineart', 'Line Art'), ('lineart_anime', 'Line Art (Anime)'), ('depth', 'Depth (MiDaS)'), ('softedge', 'Soft Edge (HED)'), ('openpose', 'OpenPose')], help_text='Type of structural control this model provides', max_length=20)),
                ('base_architecture', models.CharField(choices=[('sdxl', 'SDXL'), ('sd15', 'SD 1.5'), ('flux1', 'Flux.1'), ('qwen', 'Qwen'), ('zimage', 'Z-Image (Lumina/S3-DiT)')], default='sdxl', help_text='Base model architecture (must match paired DiffusionModel)', max_length=20)),
                ('default_conditioning_scale', models.FloatField(default=0.5, help_text='Default conditioning scale (0.5 for SDXL, 1.0 for SD1.5). Higher values follow the control image more strictly.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('default_guidance_end', models.FloatField(default=1.0, help_text='When to stop applying ControlNet (fraction of total steps, 0.0-1.0). Lower values give the model more creative freedom in later steps.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this ControlNet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ControlNet Model',
                'verbose_name_plural': 'ControlNet Models',
                'ordering': ['base_architecture', 'control_type'],
            },
        ),
    ]
