# Generated by Django 6.0.1 on 2026-02-13 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0002_add_controlnet_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffusionjob',
            name='conditioning_scale',
            field=models.FloatField(blank=True, help_text='ControlNet conditioning scale (uses ControlNet default if not set). Higher values follow the control image more strictly.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='diffusionjob',
            name='control_guidance_end',
            field=models.FloatField(blank=True, help_text='When to stop applying ControlNet (fraction of steps). Uses ControlNet default if not set.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='diffusionjob',
            name='controlnet_model',
            field=models.ForeignKey(blank=True, help_text='Optional ControlNet for structure-guided generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='diffusion.controlnetmodel'),
        ),
        migrations.AddField(
            model_name='diffusionjob',
            name='preprocessing_type',
            field=models.CharField(blank=True, choices=[('canny', 'Canny Edge'), ('lineart', 'Line Art'), ('lineart_anime', 'Line Art (Anime)'), ('depth', 'Depth (MiDaS)'), ('softedge', 'Soft Edge (HED)'), ('openpose', 'OpenPose')], default='', help_text="Preprocessing to apply to reference image. Leave blank to use ControlNet model's default control type.", max_length=20),
        ),
        migrations.AddField(
            model_name='diffusionjob',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Source image for ControlNet conditioning (e.g., extracted keyframe)', null=True, upload_to='diffusion/reference/%Y/%m/'),
        ),
    ]
