# Generated by Django 6.0.1 on 2026-02-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0007_alter_diffusionmodel_base_architecture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loramodel",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about this LoRA (usage tips, characteristics, etc.)",
            ),
        ),
    ]
