# Generated by Django 6.0.1 on 2026-02-03 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0009_loramodel_clip_skip"),
    ]

    operations = [
        migrations.AddField(
            model_name="loramodel",
            name="guidance_scale",
            field=models.FloatField(
                blank=True,
                help_text="Override guidance scale (CFG) when using this LoRA. Leave blank to use model/job default.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(20.0),
                ],
            ),
        ),
    ]
