# Generated by Django 6.0.1 on 2026-02-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0010_loramodel_guidance_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusionmodel",
            name="force_default_guidance",
            field=models.BooleanField(
                default=False,
                help_text="Force model's default guidance_scale (Turbo models). Prevents LoRA/job overrides.",
            ),
        ),
    ]
