# Generated by Django 6.0.1 on 2026-02-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0011_diffusionmodel_force_default_guidance"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusionjob",
            name="generation_metadata",
            field=models.JSONField(
                blank=True,
                help_text="Complete generation settings used (prompt, seed, parameters, etc.)",
                null=True,
            ),
        ),
    ]
