# Generated by Django 6.0.1 on 2026-02-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0012_diffusionjob_generation_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="loramodel",
            name="theme",
            field=models.CharField(
                blank=True,
                help_text="Theme or category for filtering (e.g., 'anime', 'photorealistic', 'fantasy')",
                max_length=100,
            ),
        ),
    ]
