# Generated by Django 6.0.1 on 2026-02-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0017_adaptationmarket_tvspot_tvspotversion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tvspotversion",
            name="market",
        ),
        migrations.AlterUniqueTogether(
            name="storyboardimage",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="storyboardimage",
            name="diffusion_job",
        ),
        migrations.RemoveField(
            model_name="storyboardimage",
            name="script_row",
        ),
        migrations.RemoveField(
            model_name="storyboardimage",
            name="storyboard_job",
        ),
        migrations.RemoveField(
            model_name="storyboardjob",
            name="diffusion_model",
        ),
        migrations.RemoveField(
            model_name="storyboardjob",
            name="lora_model",
        ),
        migrations.RemoveField(
            model_name="storyboardjob",
            name="tv_spot_version",
        ),
        migrations.RemoveField(
            model_name="tvspotversion",
            name="tv_spot",
        ),
        migrations.AlterUniqueTogether(
            name="tvspotscriptrow",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tvspotscriptrow",
            name="tv_spot_version",
        ),
        migrations.AlterUniqueTogether(
            name="tvspotversion",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="AdaptationMarket",
        ),
        migrations.DeleteModel(
            name="StoryboardImage",
        ),
        migrations.DeleteModel(
            name="StoryboardJob",
        ),
        migrations.DeleteModel(
            name="TvSpot",
        ),
        migrations.DeleteModel(
            name="TvSpotScriptRow",
        ),
        migrations.DeleteModel(
            name="TvSpotVersion",
        ),
    ]
