# Generated by Django 6.0.1 on 2026-02-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0004_add_float8_dtype_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loramodel',
            name='compatible_models',
        ),
        migrations.AddField(
            model_name='diffusionmodel',
            name='base_architecture',
            field=models.CharField(choices=[('sdxl', 'SDXL'), ('sd15', 'SD 1.5'), ('flux', 'Flux'), ('flux1', 'Flux.1'), ('qwen', 'Qwen')], default='sdxl', help_text='Base model architecture (determines LoRA compatibility)', max_length=20),
        ),
        migrations.AddField(
            model_name='loramodel',
            name='base_architecture',
            field=models.CharField(choices=[('sdxl', 'SDXL'), ('sd15', 'SD 1.5'), ('flux', 'Flux'), ('flux1', 'Flux.1'), ('qwen', 'Qwen')], default='sdxl', help_text='Base model architecture this LoRA is trained for', max_length=20),
        ),
    ]
