# Generated by Django 6.0.1 on 2026-02-03 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0008_loramodel_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="loramodel",
            name="clip_skip",
            field=models.IntegerField(
                blank=True,
                help_text="Number of CLIP layers to skip (1-12). Leave blank to use model default. Commonly 1 or 2 for anime/artistic styles.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
