# Generated by Django 6.0.1 on 2026-02-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0013_add_lora_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='diffusionjob',
            name='scheduler',
            field=models.CharField(blank=True, help_text="Override scheduler (e.g., 'EulerDiscreteScheduler'). Leave blank to use model default.", max_length=100),
        ),
    ]
