# Generated by Django 6.0.1 on 2026-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0014_add_scheduler_to_diffusionjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diffusionjob',
            name='scheduler',
            field=models.CharField(blank=True, choices=[('', '— Use pipeline default —'), ('EulerDiscreteScheduler', 'Euler'), ('EulerAncestralDiscreteScheduler', 'Euler Ancestral'), ('DPMSolverMultistepScheduler', 'DPM++ 2M'), ('DPMSolverSinglestepScheduler', 'DPM++ SDE'), ('KDPM2DiscreteScheduler', 'DPM2'), ('KDPM2AncestralDiscreteScheduler', 'DPM2 Ancestral'), ('FlowMatchEulerDiscreteScheduler', 'Flow Match Euler'), ('DDIMScheduler', 'DDIM'), ('DDPMScheduler', 'DDPM'), ('PNDMScheduler', 'PNDM'), ('HeunDiscreteScheduler', 'Heun'), ('LMSDiscreteScheduler', 'LMS'), ('UniPCMultistepScheduler', 'UniPC'), ('LCMScheduler', 'LCM')], default='', help_text='Override scheduler. Leave blank to use model default.', max_length=100),
        ),
        migrations.AlterField(
            model_name='diffusionmodel',
            name='scheduler',
            field=models.CharField(blank=True, choices=[('', '— Use pipeline default —'), ('EulerDiscreteScheduler', 'Euler'), ('EulerAncestralDiscreteScheduler', 'Euler Ancestral'), ('DPMSolverMultistepScheduler', 'DPM++ 2M'), ('DPMSolverSinglestepScheduler', 'DPM++ SDE'), ('KDPM2DiscreteScheduler', 'DPM2'), ('KDPM2AncestralDiscreteScheduler', 'DPM2 Ancestral'), ('FlowMatchEulerDiscreteScheduler', 'Flow Match Euler'), ('DDIMScheduler', 'DDIM'), ('DDPMScheduler', 'DDPM'), ('PNDMScheduler', 'PNDM'), ('HeunDiscreteScheduler', 'Heun'), ('LMSDiscreteScheduler', 'LMS'), ('UniPCMultistepScheduler', 'UniPC'), ('LCMScheduler', 'LCM')], default='', help_text='Default scheduler for this model', max_length=100),
        ),
    ]
