# Generated by Django 6.0.1 on 2026-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0015_add_scheduler_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusionjob",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Optional identifier for file naming (e.g., 'hero-shot', 'product-v2')",
                max_length=100,
            ),
        ),
    ]
