# Generated by Django 6.0.1 on 2026-02-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Persona name (e.g., 'Budget-Conscious First-Timer')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this persona"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target country",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personas",
                        to="audiences.country",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target language",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personas",
                        to="audiences.language",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target region",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="personas",
                        to="audiences.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "audiences_persona",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DEMOGRAPHIC", "Demographic"),
                            ("BEHAVIORAL", "Behavioral"),
                            ("PSYCHOGRAPHIC", "Psychographic"),
                        ],
                        help_text="Segment category",
                        max_length=20,
                    ),
                ),
                (
                    "vector",
                    models.CharField(
                        help_text="Dimension being segmented (e.g., 'Household Income', 'Emotional Driver')",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Position on the dimension (e.g., 'Middle-Income', 'Escapism')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional longer description"
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=list,
                        help_text="Structured insights: [{heading, points[]}]",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "db_table": "audiences_segment",
                "ordering": ["category", "vector", "value"],
                "unique_together": {("category", "vector", "value")},
            },
        ),
        migrations.CreateModel(
            name="PersonaSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="Display order (lower = earlier)"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audiences.persona",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audiences.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Segment",
                "verbose_name_plural": "Persona Segments",
                "db_table": "audiences_persona_segment",
                "ordering": ["order_index", "segment__category", "segment__vector"],
                "unique_together": {("persona", "segment")},
            },
        ),
        migrations.AddField(
            model_name="persona",
            name="segments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Demographic, behavioral, and psychographic segments",
                related_name="personas",
                through="audiences.PersonaSegment",
                to="audiences.segment",
            ),
        ),
    ]
