# Generated by Django 6.0.1 on 2026-02-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audiences", "0002_persona_segment_personasegment_persona_segments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personasegment",
            options={
                "ordering": ["segment__category", "segment__vector", "segment__value"],
                "verbose_name": "Persona Segment",
                "verbose_name_plural": "Persona Segments",
            },
        ),
        migrations.RemoveField(
            model_name="personasegment",
            name="order_index",
        ),
    ]
