# Generated by Django 6.0.1 on 2026-02-11 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0003_remove_persona_segment_order_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WVSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.IntegerField(help_text='WVS wave number (1-7)')),
                ('raw_data', models.JSONField(default=dict, help_text='All WVS variable means: {variable_code: value}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Country this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wvs_profiles', to='audiences.country')),
            ],
            options={
                'verbose_name': 'WVS Profile',
                'verbose_name_plural': 'WVS Profiles',
                'db_table': 'audiences_wvs_profile',
                'ordering': ['country__code', '-wave'],
                'unique_together': {('country', 'wave')},
            },
        ),
    ]
