# Generated by Django 6.0.1 on 2026-02-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_add_llmmodel_load_in_4bit"),
        ("diffusion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_unit_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video"),
                            ("AUDIO", "Audio"),
                            ("PRINT", "Print"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "origin_or_adaptation",
                    models.CharField(
                        choices=[("ORIGIN", "Origin"), ("ADAPTATION", "Adaptation")],
                        default="ORIGIN",
                        help_text="Is this an origin or adapted version?",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Version code (e.g., 'US-EN-001', 'DE-DE-002')",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive title for this ad unit",
                        max_length=200,
                    ),
                ),
                (
                    "use_pipeline",
                    models.BooleanField(
                        default=False,
                        help_text="Use multi-agent pipeline for adaptation",
                    ),
                ),
                (
                    "concept_brief",
                    models.JSONField(
                        blank=True,
                        help_text="Concept extraction from pipeline",
                        null=True,
                    ),
                ),
                (
                    "cultural_brief",
                    models.JSONField(
                        blank=True,
                        help_text="Cultural research from pipeline",
                        null=True,
                    ),
                ),
                (
                    "evaluation_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Evaluation results from pipeline",
                    ),
                ),
                (
                    "pipeline_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pipeline timing and model info",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("concept_analysis", "Concept Analysis"),
                            ("cultural_analysis", "Cultural Analysis"),
                            ("writing", "Writing"),
                            ("cultural_evaluation", "Cultural Evaluation"),
                            ("concept_evaluation", "Concept Evaluation"),
                            ("revising", "Revising"),
                        ],
                        default="completed",
                        max_length=30,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for async processing",
                        max_length=255,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target country (for adaptations)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad_units",
                        to="core.country",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target language (for adaptations)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad_units",
                        to="core.language",
                    ),
                ),
                (
                    "llm_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override language's primary LLM model",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad_units",
                        to="core.llmmodel",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target region (for adaptations)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad_units",
                        to="core.region",
                    ),
                ),
                (
                    "source_ad_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source ad unit this was adapted from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_units",
                        to="tvspots.adunit",
                    ),
                ),
            ],
            options={
                "db_table": "tvspots_adunit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="Internal tracking ID (e.g., 'ACME-2024-001')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "script_title",
                    models.CharField(help_text="Campaign/script title", max_length=200),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("brand_name", models.CharField(blank=True, max_length=200)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                (
                    "original_script_data",
                    models.JSONField(help_text="Original script content as JSON"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "tvspots_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoAdUnit",
            fields=[
                (
                    "adunit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tvspots.adunit",
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration in seconds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "visual_style_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Common visual style applied to all script rows",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Ad Unit",
                "verbose_name_plural": "Video Ad Units",
                "db_table": "tvspots_videoadunit",
            },
            bases=("tvspots.adunit",),
        ),
        migrations.CreateModel(
            name="AdUnitScriptRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.IntegerField(help_text="Row order (0-based)")),
                (
                    "shot_number",
                    models.CharField(
                        blank=True, help_text="Shot/scene number", max_length=10
                    ),
                ),
                (
                    "timecode",
                    models.CharField(
                        blank=True,
                        help_text="Timecode (HH:MM:SS:FF or HH:MM:SS.mmm)",
                        max_length=20,
                    ),
                ),
                (
                    "visual_text",
                    models.TextField(help_text="Visual/video column content"),
                ),
                (
                    "audio_text",
                    models.TextField(
                        blank=True, help_text="Audio/dialogue column content"
                    ),
                ),
                (
                    "ad_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_rows",
                        to="tvspots.adunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Unit Script Row",
                "verbose_name_plural": "Ad Unit Script Rows",
                "db_table": "tvspots_adunitscriptrow",
                "ordering": ["ad_unit", "order_index"],
                "unique_together": {("ad_unit", "order_index")},
            },
        ),
        migrations.AddField(
            model_name="adunit",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_units",
                to="tvspots.campaign",
            ),
        ),
        migrations.CreateModel(
            name="Storyboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images_per_row",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of images to generate per script row",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "diffusion_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storyboards",
                        to="diffusion.diffusionmodel",
                    ),
                ),
                (
                    "lora_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storyboards",
                        to="diffusion.loramodel",
                    ),
                ),
                (
                    "video_ad_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storyboards",
                        to="tvspots.videoadunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storyboard",
                "verbose_name_plural": "Storyboards",
                "db_table": "tvspots_storyboard",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryboardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_index",
                    models.IntegerField(
                        help_text="Image number for this script row (0-based)"
                    ),
                ),
                (
                    "diffusion_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storyboard_image",
                        to="diffusion.diffusionjob",
                    ),
                ),
                (
                    "script_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storyboard_images",
                        to="tvspots.adunitscriptrow",
                    ),
                ),
                (
                    "storyboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tvspots.storyboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storyboard Image",
                "verbose_name_plural": "Storyboard Images",
                "db_table": "tvspots_storyboardimage",
                "ordering": ["storyboard", "script_row__order_index", "image_index"],
            },
        ),
        migrations.AddIndex(
            model_name="adunit",
            index=models.Index(
                fields=["campaign", "ad_unit_type"],
                name="tvspots_adu_campaig_412bd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="adunit",
            index=models.Index(fields=["status"], name="tvspots_adu_status_c08890_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="storyboardimage",
            unique_together={("storyboard", "script_row", "image_index")},
        ),
    ]
