# Generated by Django 6.0.1 on 2026-02-05 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for tracking.', max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('origin_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_jobs_as_origin', to='tvspots.tvspotversion')),
                ('result_version', models.OneToOneField(blank=True, help_text='The created adaptation version (set on completion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptation_job_result', to='tvspots.tvspotversion')),
                ('target_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adaptation_jobs', to='tvspots.adaptationmarket')),
                ('tv_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_jobs', to='tvspots.tvspot')),
            ],
            options={
                'verbose_name': 'Adaptation Job',
                'verbose_name_plural': 'Adaptation Jobs',
                'db_table': 'diffusion_adaptationjob',
                'ordering': ['-created_at'],
            },
        ),
    ]
