# Generated by Django 6.0.1 on 2026-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adunit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('concept_analysis', 'Concept Analysis'), ('cultural_analysis', 'Cultural Analysis'), ('writing', 'Writing'), ('format_evaluation', 'Format Evaluation'), ('cultural_evaluation', 'Cultural Evaluation'), ('concept_evaluation', 'Concept Evaluation'), ('revising', 'Revising')], default='completed', max_length=30),
        ),
    ]
