# Generated by Django 6.0.1 on 2026-02-08 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiences", "0001_initial"),
        ("tvspots", "0002_alter_adunit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adunit",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Target country (for adaptations)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ad_units",
                to="audiences.country",
            ),
        ),
        migrations.AlterField(
            model_name="adunit",
            name="language",
            field=models.ForeignKey(
                blank=True,
                help_text="Target language (for adaptations)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ad_units",
                to="audiences.language",
            ),
        ),
        migrations.AlterField(
            model_name="adunit",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Target region (for adaptations)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ad_units",
                to="audiences.region",
            ),
        ),
    ]
