# Generated by Django 6.0.1 on 2026-02-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0002_add_adaptation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationmarket',
            name='language',
            field=models.CharField(default='en', help_text="Target language code for dialogue/VO (e.g., 'de', 'es-MX', 'ja').", max_length=10),
        ),
    ]
