# Generated by Django 6.0.1 on 2026-02-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0003_add_language_to_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationmarket',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans (af)'), ('sq', 'Albanian (sq)'), ('ar', 'Arabic (ar)'), ('hy', 'Armenian (hy)'), ('az', 'Azerbaijani (az)'), ('eu', 'Basque (eu)'), ('be', 'Belarusian (be)'), ('bn', 'Bengali (bn)'), ('bs', 'Bosnian (bs)'), ('bg', 'Bulgarian (bg)'), ('ca', 'Catalan (ca)'), ('zh', 'Chinese (zh)'), ('zh-CN', 'Chinese Simplified (zh-CN)'), ('zh-TW', 'Chinese Traditional (zh-TW)'), ('hr', 'Croatian (hr)'), ('cs', 'Czech (cs)'), ('da', 'Danish (da)'), ('nl', 'Dutch (nl)'), ('en', 'English (en)'), ('en-GB', 'English UK (en-GB)'), ('en-US', 'English US (en-US)'), ('et', 'Estonian (et)'), ('fil', 'Filipino (fil)'), ('fi', 'Finnish (fi)'), ('fr', 'French (fr)'), ('fr-CA', 'French Canadian (fr-CA)'), ('gl', 'Galician (gl)'), ('ka', 'Georgian (ka)'), ('de', 'German (de)'), ('de-AT', 'German Austrian (de-AT)'), ('de-CH', 'German Swiss (de-CH)'), ('el', 'Greek (el)'), ('gu', 'Gujarati (gu)'), ('he', 'Hebrew (he)'), ('hi', 'Hindi (hi)'), ('hu', 'Hungarian (hu)'), ('is', 'Icelandic (is)'), ('id', 'Indonesian (id)'), ('ga', 'Irish (ga)'), ('it', 'Italian (it)'), ('ja', 'Japanese (ja)'), ('kn', 'Kannada (kn)'), ('kk', 'Kazakh (kk)'), ('ko', 'Korean (ko)'), ('lv', 'Latvian (lv)'), ('lt', 'Lithuanian (lt)'), ('mk', 'Macedonian (mk)'), ('ms', 'Malay (ms)'), ('ml', 'Malayalam (ml)'), ('mt', 'Maltese (mt)'), ('mr', 'Marathi (mr)'), ('mn', 'Mongolian (mn)'), ('ne', 'Nepali (ne)'), ('no', 'Norwegian (no)'), ('fa', 'Persian (fa)'), ('pl', 'Polish (pl)'), ('pt', 'Portuguese (pt)'), ('pt-BR', 'Portuguese Brazilian (pt-BR)'), ('pa', 'Punjabi (pa)'), ('ro', 'Romanian (ro)'), ('ru', 'Russian (ru)'), ('sr', 'Serbian (sr)'), ('sk', 'Slovak (sk)'), ('sl', 'Slovenian (sl)'), ('es', 'Spanish (es)'), ('es-419', 'Spanish Latin America (es-419)'), ('es-MX', 'Spanish Mexican (es-MX)'), ('sw', 'Swahili (sw)'), ('sv', 'Swedish (sv)'), ('ta', 'Tamil (ta)'), ('te', 'Telugu (te)'), ('th', 'Thai (th)'), ('tr', 'Turkish (tr)'), ('uk', 'Ukrainian (uk)'), ('ur', 'Urdu (ur)'), ('uz', 'Uzbek (uz)'), ('vi', 'Vietnamese (vi)'), ('cy', 'Welsh (cy)')], default='en', help_text='Target language for dialogue and on-screen text.', max_length=10),
        ),
    ]
