# Generated by Django 6.0.1 on 2026-02-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiences", "0002_persona_segment_personasegment_persona_segments"),
        ("tvspots", "0003_alter_adunit_country_alter_adunit_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adunit",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                help_text="Target audience persona",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_units",
                to="audiences.persona",
            ),
        ),
    ]
