# Generated by Django 6.0.1 on 2026-02-05 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tvspots', '0004_language_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adaptationmarket',
            name='language',
        ),
        migrations.AddField(
            model_name='adaptationjob',
            name='language',
            field=models.ForeignKey(blank=True, help_text="Override market's default language (e.g., for multi-language markets like Canada).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaptation_jobs', to='core.language'),
        ),
        migrations.AddField(
            model_name='adaptationjob',
            name='llm_model',
            field=models.ForeignKey(blank=True, help_text="Override language's primary model.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adaptation_jobs', to='core.llmmodel'),
        ),
        migrations.AddField(
            model_name='adaptationmarket',
            name='default_language',
            field=models.ForeignKey(blank=True, help_text='Default language for adaptations in this market.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='core.language'),
        ),
    ]
