# Generated by Django 6.0.1 on 2026-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0005_language_model_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationjob',
            name='concept_brief',
            field=models.JSONField(blank=True, help_text='Concept extraction output (populated by pipeline).', null=True),
        ),
        migrations.AddField(
            model_name='adaptationjob',
            name='cultural_brief',
            field=models.JSONField(blank=True, help_text='Cultural research output (populated by pipeline).', null=True),
        ),
        migrations.AddField(
            model_name='adaptationjob',
            name='evaluation_history',
            field=models.JSONField(blank=True, default=list, help_text='Chronological list of evaluation results from pipeline.'),
        ),
        migrations.AddField(
            model_name='adaptationjob',
            name='pipeline_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Pipeline timing, revision counts, and model info.'),
        ),
        migrations.AddField(
            model_name='adaptationjob',
            name='use_pipeline',
            field=models.BooleanField(default=False, help_text='Use multi-agent pipeline instead of single-step adaptation.'),
        ),
        migrations.AlterField(
            model_name='adaptationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('concept_analysis', 'Concept Analysis'), ('cultural_analysis', 'Cultural Analysis'), ('writing', 'Writing'), ('cultural_evaluation', 'Cultural Evaluation'), ('concept_evaluation', 'Concept Evaluation'), ('revising', 'Revising')], default='pending', max_length=30),
        ),
    ]
