# Generated by Django 6.0.1 on 2026-02-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0005_brand_guidelines_and_brand_evaluation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code (e.g., 'LAYS', 'WALKERS', 'PEPSI')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Lay's', 'Walkers')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brand overview and positioning')),
                ('guidelines', models.TextField(blank=True, help_text='Brand voice, values, visual identity, and messaging guidelines')),
                ('insights', models.JSONField(blank=True, default=list, help_text='Brand-specific patterns: [{heading, points[]}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'tvspots_brand',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='brand_guidelines',
        ),
        migrations.AddField(
            model_name='adunit',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand override for market-specific trade names', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_units', to='tvspots.brand'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Primary brand for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='tvspots.brand'),
        ),
    ]
