# Generated by Django 6.0.1 on 2026-02-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0006_brand_model_and_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunit',
            name='pipeline_model_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-node LLM model overrides: {node_key: llm_model_pk}'),
        ),
    ]
