# Generated by Django 6.0.1 on 2026-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_old_alternative_models"),
        ("tvspots", "0006_pipeline_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="adaptationmarket",
            name="countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Countries this market targets",
                related_name="markets",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="adaptationmarket",
            name="cultures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cultural characteristics relevant to this market",
                related_name="markets",
                to="core.culture",
            ),
        ),
        migrations.AddField(
            model_name="adaptationmarket",
            name="regions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Regions this market targets (e.g., North America, Nordics)",
                related_name="markets",
                to="core.region",
            ),
        ),
    ]
