# Generated by Django 6.0.1 on 2026-02-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_old_alternative_models"),
        ("tvspots", "0007_add_dimensional_context_to_market"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvspotversion",
            name="language_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,  # Nullable during migration
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tvspot_versions_temp",
                to="core.language",
                help_text="Temporary field during migration from CharField to FK",
            ),
        ),
    ]
