# Generated by Django 6.0.1 on 2026-02-09 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvspots', '0007_adunit_pipeline_model_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='brand_name',
        ),
    ]
