# Generated by Django 6.0.1 on 2026-02-10 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0008_remove_campaign_brand_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenes",
                    models.JSONField(
                        default=list,
                        help_text='List of detected scenes with metadata:\n        [{\n            "scene_number": 1,\n            "start_time": 0.0,\n            "end_time": 3.5,\n            "duration": 3.5,\n            "visual_description": "...",\n            "objects_detected": ["product", "person"],\n            "colors": ["#FF5733", "#33FF57"],\n            "lighting": "warm, golden hour",\n            "camera_angle": "medium shot",\n            "sentiment": "positive"\n        }]\n        ',
                    ),
                ),
                (
                    "script",
                    models.JSONField(
                        default=dict,
                        help_text='Structured script matching tvspot.schema.json:\n        {\n            "scenes": [\n                {\n                    "scene_number": 1,\n                    "duration": 3.5,\n                    "visual": "Description...",\n                    "audio": {\n                        "voiceover": "Text...",\n                        "music": "Description...",\n                        "sfx": "Sound effects..."\n                    },\n                    "action": "Camera movements...",\n                    "products": ["Product names"],\n                    "sentiment": "emotional tone"\n                }\n            ]\n        }\n        ',
                    ),
                ),
                (
                    "transcription",
                    models.JSONField(
                        default=dict,
                        help_text='Full audio transcription with timestamps:\n        {\n            "language": "en-US",\n            "confidence": 0.95,\n            "segments": [\n                {\n                    "start": 0.5,\n                    "end": 3.2,\n                    "text": "Transcribed text...",\n                    "speaker": "narrator",\n                    "confidence": 0.96\n                }\n            ]\n        }\n        ',
                    ),
                ),
                (
                    "visual_style",
                    models.JSONField(
                        default=dict,
                        help_text='Overall visual style analysis:\n        {\n            "dominant_colors": ["#FF5733", "#33FF57"],\n            "color_palette": "warm, inviting",\n            "lighting_style": "natural, golden hour",\n            "camera_work": "smooth pans, static shots",\n            "editing_pace": "slow, contemplative",\n            "visual_themes": ["family", "togetherness"]\n        }\n        ',
                    ),
                ),
                (
                    "objects_summary",
                    models.JSONField(
                        default=dict,
                        help_text='Aggregated object detection:\n        {\n            "products": ["Brand Product X", "Logo"],\n            "people": {"count": 4, "demographics": ["adult", "child"]},\n            "locations": ["kitchen", "dining room"],\n            "props": ["table", "chairs", "food"]\n        }\n        ',
                    ),
                ),
                (
                    "sentiment_analysis",
                    models.JSONField(
                        default=dict,
                        help_text='Overall sentiment and emotional analysis:\n        {\n            "overall_sentiment": "positive",\n            "confidence": 0.89,\n            "emotional_arc": [\n                {"time": 0, "emotion": "neutral"},\n                {"time": 10, "emotion": "warm"}\n            ],\n            "dominant_emotions": ["happiness", "warmth"]\n        }\n        ',
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text='Scene categorization:\n        ["lifestyle", "family", "product showcase"]\n        ',
                    ),
                ),
                (
                    "audience_insights",
                    models.JSONField(
                        default=dict,
                        help_text='AI-generated audience targeting insights:\n        {\n            "primary_audience": {\n                "demographics": {"age_range": "25-45", ...},\n                "psychographics": {"values": [...], ...}\n            },\n            "secondary_audiences": [...],\n            "market_potential": {\n                "high_fit_markets": ["US", "UK", "DE"],\n                "considerations": [...]\n            }\n        }\n        ',
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        help_text="Total processing time in seconds",
                        null=True,
                    ),
                ),
                (
                    "models_used",
                    models.JSONField(
                        default=dict,
                        help_text='Track which models/APIs were used:\n        {\n            "scene_detection": "PySceneDetect",\n            "transcription": "Whisper Large v3",\n            "object_detection": "YOLO v8",\n            "script_generation": "Qwen/Qwen2.5-7B-Instruct",\n            "sentiment": "distilbert-base-uncased-finetuned-sst-2-english"\n        }\n        ',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Video Processing Result",
                "verbose_name_plural": "Video Processing Results",
                "db_table": "tvspots_videoprocessingresult",
            },
        ),
        migrations.CreateModel(
            name="AdUnitMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        help_text="Uploaded MP4 video file",
                        upload_to="ad_unit_media/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                ("resolution_width", models.IntegerField(blank=True, null=True)),
                ("resolution_height", models.IntegerField(blank=True, null=True)),
                ("frame_rate", models.FloatField(blank=True, null=True)),
                ("audio_channels", models.IntegerField(blank=True, null=True)),
                ("audio_sample_rate", models.IntegerField(blank=True, null=True)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="Size in bytes", null=True
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Campaign this media belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_unit_media",
                        to="tvspots.campaign",
                    ),
                ),
                (
                    "video_ad_unit",
                    models.OneToOneField(
                        blank=True,
                        help_text="Origin VideoAdUnit created from this media",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_media",
                        to="tvspots.videoadunit",
                    ),
                ),
                (
                    "result",
                    models.OneToOneField(
                        blank=True,
                        help_text="Processing results (scenes, script, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media",
                        to="tvspots.videoprocessingresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Unit Media",
                "verbose_name_plural": "Ad Unit Media",
                "db_table": "tvspots_adunitmedia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeyFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene_number",
                    models.IntegerField(help_text="Scene this frame represents"),
                ),
                ("timestamp", models.FloatField(help_text="Time in seconds")),
                ("image", models.ImageField(upload_to="keyframes/%Y/%m/")),
                (
                    "detected_objects",
                    models.JSONField(
                        default=list,
                        help_text='Objects detected in this frame:\n        [\n            {"label": "person", "confidence": 0.95, "bbox": [x, y, w, h]},\n            {"label": "product", "confidence": 0.88, "bbox": [x, y, w, h]}\n        ]\n        ',
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        default=list,
                        help_text="Dominant colors as hex codes: ['#FF5733', '#33FF57']",
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="CLIP or similar embedding vector for similarity search",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_frames",
                        to="tvspots.videoprocessingresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Frame",
                "verbose_name_plural": "Key Frames",
                "db_table": "tvspots_keyframe",
                "ordering": ["result", "scene_number", "timestamp"],
                "unique_together": {("result", "scene_number")},
            },
        ),
    ]
