# Generated by Django 6.0.1 on 2026-02-07 03:35

from django.db import migrations


def forward_migrate_language_codes(apps, schema_editor):
    """Map TvSpotVersion.language (CharField) → language_fk (FK)."""
    TvSpotVersion = apps.get_model("tvspots", "TvSpotVersion")
    Language = apps.get_model("core", "Language")

    # Track unmapped codes for reporting
    unmapped_codes = set()
    mapped_count = 0
    unmapped_count = 0

    for version in TvSpotVersion.objects.all():
        lang_code = version.language  # CharField value

        if not lang_code:
            # Skip if CharField was already empty
            continue

        try:
            # Look up Language by code
            language = Language.objects.get(code=lang_code)
            version.language_fk = language
            version.save(update_fields=["language_fk"])
            mapped_count += 1

        except Language.DoesNotExist:
            unmapped_codes.add(lang_code)
            unmapped_count += 1
            # Log but don't fail - will handle in next migration

    # Report results
    print("\n=== Language Migration Report ===")
    print(f"✓ Mapped: {mapped_count} versions")
    if unmapped_codes:
        print(f"✗ Unmapped codes ({unmapped_count} versions): {sorted(unmapped_codes)}")
        print("ACTION REQUIRED: Create Language entries for unmapped codes or map manually")
    print("=================================\n")


def reverse_migrate_language_codes(apps, schema_editor):
    """Rollback: Clear language_fk."""
    TvSpotVersion = apps.get_model("tvspots", "TvSpotVersion")
    TvSpotVersion.objects.update(language_fk=None)


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0008_add_language_fk_temp"),
        ("core", "0003_remove_old_alternative_models"),
    ]

    operations = [
        migrations.RunPython(
            forward_migrate_language_codes,
            reverse_migrate_language_codes,
        ),
    ]
