# Generated by Django 6.0.1 on 2026-02-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0009_add_video_origin_extraction_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="original_script_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Original script content as JSON (optional, generated from video if not provided)",
            ),
        ),
    ]
