# Generated by Django 6.0.1 on 2026-02-07 03:40

from django.core.exceptions import ValidationError
from django.db import migrations


def validate_language_fk_populated(apps, schema_editor):
    """Ensure all TvSpotVersion records have language_fk set."""
    TvSpotVersion = apps.get_model("tvspots", "TvSpotVersion")

    unmapped = TvSpotVersion.objects.filter(language_fk__isnull=True)
    count = unmapped.count()

    if count > 0:
        unmapped_ids = list(unmapped.values_list("pk", flat=True)[:10])
        raise ValidationError(
            f"Migration cannot proceed: {count} TvSpotVersion records have NULL language_fk.\n"
            f"Sample IDs: {unmapped_ids}\n"
            f"ACTION: Manually map these records before continuing."
        )

    print(f"✓ Validation passed: All {TvSpotVersion.objects.count()} records have language_fk")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0009_populate_language_fk"),
    ]

    operations = [
        migrations.RunPython(
            validate_language_fk_populated,
            noop,
        ),
    ]
