# Generated by Django 6.0.1 on 2026-02-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0010_make_original_script_data_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoprocessingresult",
            name="categories",
            field=models.JSONField(
                default=dict,
                help_text='Scene categorization summary:\n        {\n            "total_scenes": 10,\n            "category_counts": {\n                "people": 6,\n                "product": 4,\n                "lifestyle": 3\n            },\n            "primary_categories": ["people", "product", "lifestyle"]\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="videoprocessingresult",
            name="models_used",
            field=models.JSONField(
                default=dict,
                help_text='Track which models/APIs were used:\n        {\n            "scene_detection": "PySceneDetect",\n            "transcription": "Whisper Large v3",\n            "object_detection": "YOLO v8x",\n            "visual_style": "OpenCV + k-means",\n            "sentiment": "keyword-based",\n            "script_generation": "Basic (MVP)"\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="videoprocessingresult",
            name="objects_summary",
            field=models.JSONField(
                default=dict,
                help_text='Aggregated object detection from YOLO v8:\n        {\n            "total_objects": 15,\n            "classes": {\n                "person": {"count": 5, "avg_confidence": 0.92},\n                "car": {"count": 2, "avg_confidence": 0.85},\n                "bottle": {"count": 3, "avg_confidence": 0.88}\n            },\n            "most_common": ["person", "car", "bottle"]\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="videoprocessingresult",
            name="sentiment_analysis",
            field=models.JSONField(
                default=dict,
                help_text='Sentiment analysis from audio and visual data:\n        {\n            "overall_sentiment": "positive",\n            "overall_score": 0.65,\n            "confidence": 0.72,\n            "text_sentiment": {\n                "sentiment": "positive",\n                "score": 0.75,\n                "confidence": 0.68\n            },\n            "visual_sentiment": {\n                "sentiment": "positive",\n                "score": 0.6,\n                "brightness_factor": 0.7,\n                "object_factor": 0.5\n            }\n        }\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="videoprocessingresult",
            name="visual_style",
            field=models.JSONField(
                default=dict,
                help_text='Overall visual style analysis from keyframes:\n        {\n            "dominant_colors": ["#FF5733", "#3357FF", ...],\n            "avg_brightness": 0.58,\n            "avg_contrast": 0.45,\n            "lighting_distribution": {"soft": 3, "harsh": 1, "dramatic": 1},\n            "exposure_distribution": {"normal": 4, "overexposed": 1},\n            "camera_work": {\n                "avg_scene_duration": 4.5,\n                "total_scenes": 12,\n                "pacing": "fast",\n                "scene_transitions": 11\n            }\n        }\n        ',
            ),
        ),
    ]
