# Generated by Django 6.0.1 on 2026-02-07 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Final migration: Remove old CharField, rename FK, make non-nullable.

    CRITICAL: This is the point of no return (without complex rollback).
    Ensure migrations 0008-0010 completed successfully before running.
    """

    dependencies = [
        ("tvspots", "0010_verify_language_fk"),
        ("core", "0003_remove_old_alternative_models"),
    ]

    operations = [
        # Step 1: Remove old CharField
        migrations.RemoveField(
            model_name="tvspotversion",
            name="language",
        ),
        # Step 2: Rename language_fk → language
        migrations.RenameField(
            model_name="tvspotversion",
            old_name="language_fk",
            new_name="language",
        ),
        # Step 3: Make FK non-nullable and update related_name
        migrations.AlterField(
            model_name="tvspotversion",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tvspot_versions",
                to="core.language",
                help_text="Language for this version",
            ),
        ),
    ]
