# Generated by Django 6.0.1 on 2026-02-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0011_update_categories_to_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="adunitmedia",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async video processing",
                max_length=255,
            ),
        ),
    ]
