# Generated by Django 6.0.1 on 2026-02-07 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_old_alternative_models"),
        ("tvspots", "0011_swap_language_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVSpotAdaptation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        help_text="Internal tracking ID for this adaptation",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title (e.g., 'Nordic Holiday Campaign 2024')",
                        max_length=200,
                    ),
                ),
                (
                    "adaptation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this adaptation (creative direction, client feedback, etc.)",
                    ),
                ),
                (
                    "script_data",
                    models.JSONField(
                        help_text="Full script content as JSON (structure matches TvSpot import format)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Primary country this adaptation targets",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adaptations",
                        to="core.country",
                    ),
                ),
                (
                    "cultures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional: Cultural characteristics relevant to this adaptation",
                        related_name="adaptations",
                        to="core.culture",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Primary language for this adaptation",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adaptations",
                        to="core.language",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Primary region this adaptation targets",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adaptations",
                        to="core.region",
                    ),
                ),
                (
                    "source_adaptation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent adaptation this was derived from (for adaptation chains)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_adaptations",
                        to="tvspots.tvspotadaptation",
                    ),
                ),
            ],
            options={
                "verbose_name": "TV Spot Adaptation",
                "verbose_name_plural": "TV Spot Adaptations",
                "db_table": "diffusion_tvspotadaptation",
                "ordering": ["-created_at"],
            },
        ),
    ]
