# Generated by Django 6.0.1 on 2026-02-07 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_old_alternative_models"),
        ("tvspots", "0012_add_tvspotadaptation_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adaptationjob",
            name="target_market",
        ),
        migrations.AddField(
            model_name="adaptationjob",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Target country for this adaptation (optional, for insights composition).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adaptation_jobs",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="adaptationjob",
            name="region",
            field=models.ForeignKey(
                default=1,
                help_text="Target region for this adaptation (required, for insights composition).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adaptation_jobs",
                to="core.region",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adaptationjob",
            name="language",
            field=models.ForeignKey(
                default=1,
                help_text="Target language for this adaptation (required).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adaptation_jobs",
                to="core.language",
            ),
            preserve_default=False,
        ),
    ]
