# Generated by Django 6.0.1 on 2026-02-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tvspots", "0013_replace_market_with_region_country_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adaptationmarket",
            name="cultures",
        ),
        migrations.RemoveField(
            model_name="tvspotadaptation",
            name="cultures",
        ),
    ]
